version: '3.9'

services:
  sale_cars:
    image: postgis/postgis
    ports:
      - '${POSTGRES_EXTERNAL_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sale_cars
    volumes:
      - sale_cars_db:/var/lib/postgresql/sale_cars

#  redis:
#    image: redis:alpine3.14
#    container_name: redis_sale-cars
#    ports:
#      - '6379:6379'

volumes:
  sale_cars_db:
#  redis: